spring:
  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
    alicloud:
      access-key: LTAI4G6MJHukz2549aDCMy1J
      secret-key: bThPe7wGCoeRVnCKCRDR7sqpibt1n4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: msw-mall
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: f5e68c3ad6b6474faa8cd178b21d3377
        appCode: cdca144fd2274ac3856017d67478eb88

  application:
    name: mall-third

server:
  port: 43000

logging:
  level:
    com.mall.third: debug
    com.alibaba.nacos.client.naming: warn