spring:
  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
    alicloud:
      access-key: LTAI4G6MJHukz2549aDCMy1J
      secret-key: bThPe7wGCoeRVnCKCRDR7sqpibt1n4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: msw-mall
  application:
    name: mall-third

server:
  port: 43000

logging:
  level:
    com.mall.third: debug
    com.alibaba.nacos.client.naming: warn