server:
  port: 51000

spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
    # 配置网关路由
    gateway:
      routes:
#        - id: baidu-route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq-route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        # product - 商品服务
        - id: product-route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon-route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # third - 第三方服务
        - id: third-route
          uri: lb://mall-third
          predicates:
            - Path=/api/third/**
          filters:
             - RewritePath=/api/third/(?<segment>.*),/$\{segment}

        # member - 会员服务
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # ware - 金融服务
        - id: ware-route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # admin - 后台管理系统
        - id: admin-route
          uri: lb://web-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/web-admin/$\{segment}


        # 将主机地址为 search.echoone.cn 的请求转发至 mall-search
        - id: search-host
          uri: lb://mall-search
          predicates:
            - Host=search.echoone.cn

        # 将主机地址为 auth.echoone.cn 的请求转发至 mall-auth
        - id: auth-host
          uri: lb://mall-auth
          predicates:
            - Host=auth.echoone.cn

        # 将主机地址为 seckill.echoone.cn 的请求转发至 mall-seckill
        - id: seckill-host
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.echoone.cn

        # 将主机地址为 cart.echoone.cn 的请求转发至 mall-cart
        - id: cart-host
          uri: lb://mall-cart
          predicates:
            - Host=cart.echoone.cn

        # 将主机地址为 member.echoone.cn 的请求转发至 mall-member
        - id: member-host
          uri: lb://mall-member
          predicates:
            - Host=member.echoone.cn

        # 将主机地址为 order.echoone.cn 的请求转发至 mall-order
        - id: order-host
          uri: lb://mall-order
          predicates:
            - Host=order.echoone.cn

        # 将主机地址为 echoone.cn / item.echoone.cn 的请求转发至 mall-product
        - id: product-host
          uri: lb://mall-product
          predicates:
            - Host=echoone.cn,item.echoone.cn

##admin-route:
# http://localhost:51000/api/captcha.jps => http://localhost:8080/web-admin/captcha.jpg

logging:
  level:
    com.mall.gateway: debug
    com.alibaba.nacos.client.naming: warn