server:
  port: 51000

spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
    # 配置网关路由
    gateway:
      routes:
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        # product - 商品服务
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # third - 第三方服务
        - id: third_route
          uri: lb://mall-third
          predicates:
            - Path=/api/third/**
          filters:
             - RewritePath=/api/third/(?<segment>.*),/$\{segment}

        # member - 会员服务
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # ware - 金融服务
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # admin - 后台管理系统
        - id: admin_route
          uri: lb://web-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/web-admin/$\{segment}

        - id: search_route
          uri: lb://mall-search
          predicates:
            - Host=search.glmall.com

        - id: auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.glmall.com

        - id: seckill_route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.glmall.com

        - id: cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.glmall.com

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Host=member.glmall.com

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Host=order.glmall.com

        # 任何以 echoone.cn 结尾的域名转发到mall-product
        - id: mall_route
          uri: lb://mall-product
          predicates:
            - Host=**.echoone.cn,echoone.cn

##admin_route:
# http://localhost:51000/api/captcha.jps => http://localhost:8080/web-admin/captcha.jpg

logging:
  level:
    com.mall.gateway: debug
    com.alibaba.nacos.client.naming: warn