server:
  port: 51000

spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
    # 配置网关路由
    gateway:
      routes:
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        # product - 商品服务
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # third - 第三方服务
        - id: third_route
          uri: lb://mall-third
          predicates:
            - Path=/api/third/**
          filters:
             - RewritePath=/api/third/(?<segment>.*),/$\{segment}

        # member - 会员服务
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # ware - 金融服务
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # admin - 后台管理系统
        - id: admin_route
          uri: lb://web-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/web-admin/$\{segment}


##admin_route:
# http://localhost:51000/api/captcha.jps => http://localhost:8080/web-admin/captcha.jpg