server:
  port: 50000

spring:
  application:
    name: mall-coupon

  datasource:
    username: root
    password: 232624
    url: jdbc:mysql://echoone:3308/guli_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848

  zipkin:
    base-url: http://echoone:9411/
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.mall.coupon: debug
    com.alibaba.nacos.client.naming: warn