server:
  port: 42000

spring:
  application:
    name: mall-auth

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: echoone
    port: 6379

  devtools:
    livereload:
      port: 35731

logging:
  level:
    com.mall.third: debug
    com.alibaba.nacos.client.naming: warn

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

#暴露所有端点,actuator 健康监控
management:
  endpoints:
    web:
      exposure:
        include: '*'