server:
  port: 55000

spring:
  datasource:
    username: root
    password: 232624
    url: jdbc:mysql://echoone:3308/guli_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
  application:
    name: mall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: echoone
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.mall.ware: debug
    com.alibaba.nacos.client.naming: warn

myRabbitmq:
  MQConfig:
    queues: stock.release.stock.queue
    delayQueue: stock.delay.queue
    eventExchange: stock-event-exchange
    routingKey: stock.locked
    letterRoutingKey: stock.release
    # 库存自动过期时间 单位:(毫秒)
    ttl: 900000