server:
  port: 54000

spring:
  application:
    name: mall-product

  datasource:
    username: root
    password: 232624
    url: jdbc:mysql://echoone:3308/guli_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: echoone
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: false
      #key-prefix: CACHE_
      cache-null-values: true

  zipkin:
    base-url: http://echoone:9411/
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除, 1代表删除, 0代表不删除
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.mall.product: debug
    com.alibaba.nacos.client.naming: warn
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

#暴露所有端点,actuator 健康监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启 feign 对 sentinel 的支持
feign:
  sentinel:
    enabled: true

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10