server:
  port: 50003

spring:
  datasource:
    username: root
    password: 232624
    url: jdbc:mysql://echoone:3308/mall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: echoone:8848
  application:
    name: mall-order

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.mall.order: debug
    com.alibaba.nacos.client.naming: warn